greeting: Hello

endpoints:
  health:
    sensitive: false

info:
  build:
    artifact: hello-spring-boot
    name: hello-spring-boot
    description: Hello Spring Boot
    version: 0.0.1-SNAPSHOT

---

spring:
  profiles: spanish

greeting: Hola